name: DummySemgrep

on:
  # Manually trigger the workflow
  workflow_dispatch:  {}

jobs:
  semgrep:
    name: DummyScan
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@v4
      - run: cp local.sarif semgrep.sarif
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
          #  Used to differentiate multiple results for one commit
          category: Semgrep OSS
        if: always()
